[package]
name = "fcsd"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"

[dev-dependencies]
rand = "0.8.4"
rand_chacha = "0.3.1"
